INSERT INTO `pd_families_beta` (`Family`) VALUES ('AVIA LX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('AVIA NX Family of Compact DPSS Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Astrella Integrated Ti:S Amplifier');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Azure');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Beam Delivery Fibers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('CH Series High Power Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('CO Laser - 5µm');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('CO2 Slab Laser');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('COMPex');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('CUBE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Chameleon Compact OPO Family');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Chameleon Discovery');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Chameleon PreComp Accessory');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Chameleon Ultra');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Chameleon VUE Harmonics Accessory');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Chameleon Vision');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('ColdRay Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Compass');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Conduction Cooled Package (CCP)');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Corelase');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DF Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DFG 9800/9850');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DIAMOND C-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DIAMOND E-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DIAMOND FLQ-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DIAMOND GEM-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DIAMOND J-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DILAS Fiber-HP-SMASMA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DILAS Fibers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('DILAS PT-Q Fiber');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Diode Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('EasyJewel');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('EasyMark');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('EnergyMax Laser Sensors');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('EnergyMax-USB/RS Sensors');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('ExciStar XS');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('External Optics');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('FAP 600 Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('FH Series High Power Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('FLARE NX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Fiber Amplifiers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Fiber Coupled Laser Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Fiber Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Fiber Optic Cables');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Fidelity HP Ultrafast Fiber Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Fidelity-2 Ultrafast Fiber Oscillator');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('G-Stack Diode Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('GL Series Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Genesis CX-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Genesis Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Genesis Taipan HD-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('GeoLasHD');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('H-LASE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('HELIOS');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('HYPER RAPID');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Harmonic Generator');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Hidra');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('HighLight DD-Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('HighLight FL');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('HighLight FL-1000P');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Horizontal Arrays');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('HyperRapid NX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('INNOVA ICE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Incoupling Optics');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('IndyStar');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Innova 300C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Innova 70C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Innova 90C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Innova FreD');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Innova Sabre');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Instrument Accessories');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('LAMBDA SX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('LEAP');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('LPXpro');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Lasag');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Laser & Amplifier Fibers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Laser Beam Diagnostics');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Laser Marking Workstations');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Laser Power and Energy Meters');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Lee Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Legend Elite Cryo PA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Legend Elite HE+');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Libra');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('LineBeam');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('MATRIX CW Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('MATRIX QS DPSS Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('META');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('META 1.5C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('META 10C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('META 2C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('META 4C');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Magnum II Laser');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Manual Laser Welding Tools');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Mephisto Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Mini Laser');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Mira 900');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Mira-HP');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Mira-OPO');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Modular Processing Systems');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Monaco');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuBEAM');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuBRIDGE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuCOAT-FA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuCOMM');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuEYDF');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuGYRO');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuMATCH');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuPANDA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuSENSOR');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuTDF');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuVIEW');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuWIRE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuXLMA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('NuYDF');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('O-LASE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('OBIS');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('OBIS CORE LS');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('OBIS CellX Laser Beam Combiner');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('OBIS Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('OPA 9800/9850');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('OPerA Solo kHz OPA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Opera-F and Opera-HP for Monaco');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PLS Series Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PRC Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Paladin Advanced 355');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Paladin Advanced 532');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Paladin Compact 355');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Performance Family');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerLine E');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerLine F');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerLine L');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerLine Laser');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerLine Pico');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerLine Prime');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerMax USB/RS Sensors');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerMax-Pro Sensor');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('PowerMax-Pro USB/RS Sensors');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Pulse Compressors');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Pulse PIcker');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Pulse Switch for Mira 900');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('RAPID');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('RAPID FX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('RAPID NX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Reduced Price Power Meter/Sensor Kits');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('RegA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Revolution');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('SUPER RAPID-HE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Sapphire');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Sapphire Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Select');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Sensors - Laser Power');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Single Emitter Diode Lasers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Single-Mode Fibers');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Staccato');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StarCut Tube');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StarFemto FX');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StarFiber 100-600');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StarPulse');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StarShape');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StingRay Accessories');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StingRay Developers Kit');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('StingRay and BioRay Laser Diode Modules');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Synchrolock-AP');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('TOPAS-Prime kHz OPA');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Tinsley Custom Optics');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('UVblade');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Ultra Low-Noise Laser Diode Modules');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Unmounted Diode Laser Bars');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('VYPER');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('VarioLas Family');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Verdi G Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Verdi V Series');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Vitara');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('Vitara-CEP Stabilizer');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('X-LASE');
INSERT INTO `pd_families_beta` (`Family`) VALUES ('kW PowerMax-Pro Sensor');
